### ISSUE TITLE
Asynchronous Multi-agent Rainbow

### ISSUE THREAD

**Issue by marintoro** [Kaixhin/Rainbow#20]
Hi,

I am currently using your code to communicate with the autonomous car simulator Carla, for the moment it's showing decent result (at least it can learn something).
I will now implement asynchronous multi-agent for Rainbow and before starting doing it, I just wanted to know if you already worked on it?
I will submit a pull request when it will be ready if it's ok for you.

**Comment by Kaixhin** [comment]
I'm trying to keep this as close to the original paper as possible. If you've got performance improvements then they'd be very welcome, or possibly generalisations that don't add much to the code/runtime, but otherwise it's probably better to either keep a separate fork or a new repository as appropriate.
