### ISSUE TITLE
Quick questions on the Quantile loss function

### ISSUE THREAD

**Issue by hohoCode** [Kaixhin/Rainbow#21]
https://github.com/Kaixhin/Rainbow/blob/cf4c3153777c4fddd15dfa09dcf04878fce5640a/agent.py#L62-L67

Great codes. Thanks. 

In terms of the action selection, at least from the 'ShangtongZhang for DeepRL' repository, it just seems to me the Quantile loss (or maybe also the Categorical loss) selects the action with the target network, instead of the online_net as done in your code? Just seems to me there is a difference from typical ways of implementing the Quantile loss? 

Also I am wondering Quantile vs Categorical in generale which one is better according to your experiments? Thanks.

**Comment by Kaixhin** [comment]
This repo has the [double Q-learning update rule](https://arxiv.org/abs/1509.06461), which uses the online network for action selection and target network for the value to prevent overestimation. It can be applied to any such update.

I don't have the time or resources to compare the two, I just added it in because it seemed a small enough change to Rainbow, and in general I'm not planning to add extra things on top of Rainbow. If you run experiments then let me know what you find!
