### ISSUE TITLE
To run a demo

### ISSUE THREAD

**Issue by zyzhang1130** [Kaixhin/Rainbow#65]
Hi, may I ask after the training is how should I run the trained agent to perform the task in with its fixed parameters for demonstration of its performance?

Thank you.

**Comment by Kaixhin** [comment]
If you read the `main` file, you'll see adding the [`--evaluate`](https://github.com/Kaixhin/Rainbow/blob/master/main.py#L48) argument on the command line will do this. This combines with [`--model <model_path>`](https://github.com/Kaixhin/Rainbow/blob/master/main.py#L35) for loading a saved agent. [This](https://github.com/Kaixhin/Rainbow/blob/master/main.py#L137-L140) is how evaluation is done, instead of training the model.

**Comment by zyzhang1130** [comment]
noted with thanks. I will try it out.
